spring.application.name=Agenda


server.port=8010

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xe
spring.datasource.username=system
spring.datasource.password=12345
spring.datasource.driver-class-name.jdbc.OracleDriver
spring.jps.database=ORACLE
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.database.hibernate.format-sql=true